name: RepoAworkflow

on:
  push:
 
jobs:
  RepoAjobs:
    runs-on: [ubuntu-latest]
    steps:
      - name: test
        run: |
          echo test
      - name: send dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PAT}}
          event-type: RepoAevent
