name: RepoAworkflow

on:
  push:
    tags:
    - 'publish-v*'
 
jobs:
  RepoAjobs:
    runs-on: [ubuntu-latest]
    steps:
      - name: test
        run: |
          echo test
      - name: send dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          repository: agahkarakuzu/test-repo-A
          event-type: RepoAevent
